# Generated by Django 4.2.16 on 2025-01-14 21:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_librarian",
                    models.BooleanField(db_column="is_librarian", default=False),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "bookID",
                    models.AutoField(
                        db_column="bookid", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="api.author"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "genreID",
                    models.AutoField(
                        db_column="genreid", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "languageID",
                    models.AutoField(
                        db_column="languageid", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("shortcut", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "db_table": "languages",
            },
        ),
        migrations.CreateModel(
            name="LibrarianKeys",
            fields=[
                (
                    "librarian_key",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "librarian_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "inventoryID",
                    models.AutoField(
                        db_column="inventoryid", primary_key=True, serialize=False
                    ),
                ),
                ("total_copies", models.IntegerField(default=0)),
                ("available_copies", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.book"
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="BorrowedBook",
            fields=[
                (
                    "borrowed_id",
                    models.AutoField(
                        db_column="borrowedid", primary_key=True, serialize=False
                    ),
                ),
                ("borrowed_date", models.DateField(default=datetime.date.today)),
                ("returned_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Reserved", "Resevered"),
                            ("Picked up", "Picked up"),
                            ("Returned", "Returned"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Reserved",
                        max_length=50,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookQueue",
            fields=[
                (
                    "book_queue_id",
                    models.AutoField(
                        db_column="book_queueid", primary_key=True, serialize=False
                    ),
                ),
                ("queue_date", models.DateField(default=datetime.date.today)),
                ("turn", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.genre",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="borrowed_books",
            field=models.ManyToManyField(
                related_name="borrowers", through="api.BorrowedBook", to="api.book"
            ),
        ),
    ]
