# Generated by Django 4.2.18 on 2025-01-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_path",
            field=models.CharField(
                blank=True, default="null", max_length=255, null=True
            ),
        ),
    ]
