apiVersion: v1
kind: Service
metadata:
  name: library-management-system-backend-service
  labels:
    app: library-management-system-backend-service
spec:
  type: NodePort
  selector:
    app: library-management-system-backend
  ports:
    - port: 8000
      targetPort: 8000