apiVersion: apps/v1
kind: Deployment
metadata:
    name: library-management-system-frontend
    labels:
        app: library-management-system-frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: library-management-system-frontend
    template:
        metadata:
            labels:
                app: library-management-system-frontend
        spec:
            containers:
            -   name: frontend-k8s
                image: pekoraptor/library-management-system:frontend-k8s
                ports:
                -   containerPort: 80