apiVersion: v1
kind: Service
metadata:
  name: library-management-system-frontend-service
  labels:
    app: library-management-system-frontend-service
spec:
  type: NodePort
  selector:
    app: library-management-system-frontend
  ports:
    - port: 80
      targetPort: 80
