name: Run Vitest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'


      - name: Install dependencies
        run: |
          npm install
        working-directory: frontend/library-management-system

      # Run Vitest tests
      - name: Run tests
        run: |
          npm run test
        working-directory: frontend/library-management-system
